Statically determine if a cache adapter is enabled.
In `Adaptable::enabled()` it first asks for an instance of the adapter, which might be fine with other adaptables but for caching this does not work correctly since you could get a fatal error.

~~~
Fatal error: Class 'Memcached' not found
~~~